config:
  target: "http://localhost:3000"
  phases:
    - name: "ARTILLERIES TESTS ARE COMING"  
      duration: 60   
      arrivalRate: 5  
  variables:
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3NGNjNDAyZGEyMzA3YmUxMDYwMDEzNyIsInVzZXJuYW1lIjoicGF1bCIsInBhc3N3b3JkIjoiJDJhJDEwJFdxZ2FIN0haMzVYMnBZMFBTR3NoSy5xWS5jRjdRaExXRWNzanA0RGsxT0Izd3Q1LmFxYmNpIiwiZW1haWwiOiJnYXl0YW5nQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsIl9fdiI6MH0sImlhdCI6MTczNDM3OTY1NCwiZXhwIjoxNzM0MzgzMjU0fQ.ON3BgGy3GZQ4QR6iGcCK9Ry1rQNfHRil6QbUWKFFjt8"
  defaults:
    headers:
      Authorization: "Bearer {{ token }}"
      Content-Type: "application/json"

scenarios:
  - name: Create a New User
    flow:
      - post:
          url: "/users/signIn"
          json:
            username: "artillery"
            password: "artilleryPassword"
            email: "artilleryTest@gmail.com"
            role: "User"
          expect:
            statusCode: 201

  - name: Login user
    flow:
      - get:
          url: "/users/login"
          json:
            email: "artilleryTest@gmail.com"
            password: "artilleryPassword"
          expect:
            statusCode: 200



  - name: Update a user
    flow:
      - put:
          url: "/users/6736b6716e8eb4c9228fe3b1"
          json:
            username: "test"
            password: "gaytangDugrandPré"
            email: "artilleryTestMod@gmail.com"
            role: "User"
          expect:
            statusCode: 200

  - name: Delete a user
    flow:
      - delete:
          url: "/users/6736b6716e8eb4c9228fe3b1"
          expect:
            statusCode: 204

  - name: get all teamInfos
    flow:
      - get:
          url: "/teamInfos"
          expect:
            statusCode: 200


  - name: get all points
    flow:
      - get:
          url: "/points"
          expect:
            statusCode: 200


  - name: get all games
    flow:
      - get:
          url: "/games"
          expect:
            statusCode: 200

